baseurl: https://ifsc.results.info/api/v1/
year: 2025
headers:
    "accept": "application/json"
    "accept-encoding": "gzip, deflate, br, zstd"
    "accept-language": "en-GB,en;q=0.6"
    "referer": "https://ifsc.results.info/"
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"